name: Build Atmosphere-NX
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04  # Use stable runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install devkitPro
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential wget python3 python3-pip liblz4-dev
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          sudo dpkg -i install-devkitpro-pacman
          sudo dkp-pacman -Syu
          sudo dkp-pacman -S switch-dev devkitA64 --noconfirm
          pip3 install pyelftools

      - name: Set up devkitPro environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITPPC=/opt/devkitpro/devkitPPC" >> $GITHUB_ENV
          echo "/opt/devkitpro/tools/bin" >> $GITHUB_PATH  # Add tools to PATH
          echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

      - name: Verify devkitPro tools
        run: |
          aarch64-none-elf-gcc --version  # Check compiler
          make --version
          python3 --version

      - name: Build Atmosphere
        run: |
          make -j$(nproc) || { echo "Build failed"; exit 1; }  # Explicit error handling

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/bootloader/payloads
          cp fusee/bin/fusee.bin artifacts/bootloader/payloads/
          cp -r out/* artifacts/

      - name: Upload Atmosphere artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-artifacts
          path: artifacts/
          if-no-files-found: error
          retention-days: 5

      - name: Commit artifacts to repository
        if: github.event_name == 'push'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add artifacts/
          git diff-index --quiet HEAD || git commit -m "Add compiled Atmosphere artifacts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true  # Prevent failure on empty commits
